---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# TODO Is this necessary?
env:
  # Currently no way to detect automatically
  DEFAULT_BRANCH: main

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO This came from https://github.com/onedr0p/home-ops/blob/main/.github/workflows/lint.yaml
      #     Check if this is necessary.
      # - name: Generate Token
      #   uses: tibdex/github-app-token@v1
      #   id: generate-token
      #   with:
      #     app_id: "${{ secrets.BOT_APP_ID }}"
      #     private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: MegaLinter
        uses: oxsecurity/megalinter@v6.1.0
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          # TODO Check if this is ok
          VALIDATE_ALL_CODEBASE: false
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "ANSIBLE_ANSIBLE_LINT",
                    "COPYPASTE_JSCPD",
                    "KUBERNETES_KUBEVAL",
                    "MARKDOWN_MARKDOWNLINT",
                    "REPOSITORY_GIT_DIFF",
                    "REPOSITORY_SECRETLINT",
                    "TERRAFORM_TERRAFORM_FMT",
                    "YAML_PRETTIER",
                    "YAML_YAMLLINT"
                  ]
                '),
                ','
              )
            }}
          ANSIBLE_DIRECTORY: provision/ansible
          ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .github/linters/.ansible-lint
          KUBERNETES_DIRECTORY: cluster
          KUBERNETES_KUBEVAL_ARGUMENTS: --ignore-missing-schemas
          KUBERNETES_KUBEVAL_FILTER_REGEX_INCLUDE: "(kubernetes)"
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/.markdownlint.yaml
          MARKDOWN_MARKDOWNLINT_RULES_PATH: .github/
          YAML_YAMLLINT_CONFIG_FILE: .github/linters/.yamllint.yaml
          YAML_PRETTIER_CONFIG_FILE: .github/linters/.prettierrc.yaml
          YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(.*\\.sops\\.ya?ml)"
